FROM maven:3-eclipse-temurin-8-alpine as builder

ADD ./server/ /root/server/
WORKDIR /root/server/
RUN mvn install

FROM eclipse-temurin:8-alpine

# TODO
COPY --from=builder /root/server/ /root/server/
ENTRYPOINT ["java", "-jar", "/root/server/app.jar"]
EXPOSE 8080
