FROM registry.oracle.com/graalvm/community:ol9-java17-22 as builder

ADD ./server/ /root/server/
WORKDIR /root/server/
RUN java -version
RUN echo $GRAALVM_HOME
RUN gu install native-image
RUN bash ./mvnw --batch-mode clean package -Pnative

FROM ubuntu:latest

COPY --from=builder /root/server/target/cloudnative2023 /root/server/target/cloudnative2023
ENTRYPOINT ["/root/server/target/cloudnative2023", "-Djavax.xml.accessExternalDTD=all"]
EXPOSE 8080
