server:
  port: 8080   #配置本服务器的端口为8080
spring:
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:testdb}?useSSL=false&serverTimezone=CST&allowMultiQueries=true
    username: ${DB_USER:test}
    password: ${DB_PASS:test}

#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.imaegoo.cloudnative2023.entity
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true
